# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f364ae708ae7cfec956652fd0a88ccd41d21c82c2d8e056de8abbe95bea2eaa47e94d13fa3daef6bb2b3a896363c4eea37a415489446b64ae6fcfa9251681297

test:
  secret_key_base: 030687712faf6ee2b82e287a1d40f1e5d2b319427485a2bea862ae504ca79ace6cd74b326f6a6a82579db7016b1c8d65895e63a69e14b1582ede9d6c316ddf00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
